import React, { useEffect, useMemo, useState } from 'react';
import { Alert, Image, Linking, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { Asset } from 'expo-asset';
const logo = require('./logo.jpeg');
const csvAsset = require('./chat.csv');

const categorias=['Bovinos','Suínos','Frangos','Churrasco','Peixes','Mercearia','Bebidas Alcoólicas','Refrigerantes','Energéticos','Sucos','Águas','Outras Bebidas','Padaria','Hortfruti','Laticínios','Limpeza','Perfumaria','Utensílios Domésticos','Animal'];
const emoji={Bovinos:'🥩',Suínos:'🥓',Frangos:'🍗',Churrasco:'🔥',Peixes:'🐟',Mercearia:'🛒',Bebidas:'🥤','Bebidas Alcoólicas':'🍺',Refrigerantes:'🥤',Energéticos:'⚡',Sucos:'🧃',Águas:'💧','Outras Bebidas':'🥛',Padaria:'🥖',Hortfruti:'🍎',Laticínios:'🧀',Limpeza:'🧹',Perfumaria:'🧴','Utensílios Domésticos':'🍴',Animal:'🐾'};
const dinheiro=v=>`R$ ${Number(v||0).toFixed(2).replace('.',',')}`;
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const parsePreco=s=>Number(String(s||'0').replace(/R\$\s?/g,'').replace(/\./g,'').replace(',','.'))||0;
function parseCSV(text){
 const rows=[]; let row=[],cell='',q=false;
 for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1]; if(c==='"'){if(q&&n==='"'){cell+='"';i++;}else q=!q;}else if(c===','&&!q){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}
 if(cell||row.length){row.push(cell);rows.push(row);} return rows;
}
function classificar(nome,categoria,ncm){
 const n=norm(nome),c=norm(categoria);
 if((n.includes('FILE DE TILAPIA')||n.includes('FILE DE MERLUZA'))&&!n.includes('ISCA')) return 'Peixes';
 if(/TILAPIA|MERLUZA|BACALHAU|PEIXE/.test(n)) return null;
 if(c==='BEBIDAS') return 'Bebidas';
 if(c==='HORTFRUTI') return 'Hortfruti';
 if(c==='MERCEARIA'){
  if(/ARROZ|FEIJAO|ACUCAR|OLEO|AZEITE|CAFE|MACARRAO|MASSA|MOLHO|EXTRATO DE TOMATE|LEITE|NESCAU|ACHOCOLAT|LEITE EM PO|FARINHA|FUBA|SAL |SAL$|TEMPERO|VINAGRE|MAIONESE|KETCHUP|MOSTARDA|SARDINHA|ATUM|MILHO|ERVILHA|PALMITO|AVEIA|FAROFA/.test(n)) return 'Mercearia';
  return null;
}
 if(c==='PADARIA') return 'Padaria';
 if(c==='LATICINIOS') return 'Laticínios';
 if(c==='LIMPEZA') return 'Limpeza';
 if(c==='PERFUMARIA') return 'Perfumaria';
 if(c==='UTENSILIOS DOMESTICOS') return 'Utensílios Domésticos';
 if(c==='ANIMAL') return 'Animal';
 if(/LINGUICA|ESPETO|CARVAO|SAL GROSSO|PAO DE ALHO|QUEIJO COALHO/.test(n)) return 'Churrasco';
 if(/FRANGO|COXA|COXINHA|SOBRECOXA|(^| )ASA($| )|MEIO DA ASA|TULIPA|SASSAMI|PEITO DE FRANGO|FILE DE COXA|GALINHA|CORACAO DE FRANGO/.test(n)) return 'Frangos';
 if(/SUIN|PORCO|PANCETA|BISTECA|LOMBO|PERNIL|COSTELA SUINA|BARRIGA|BANHA/.test(n)) return 'Suínos';
 if(/PICANHA|ALCATRA|ACEM|PATINHO|COXAO|CONTRA FILE|CONTRAFILE|MAMINHA|FRALDINHA|CUPIM|MUSCULO|PALETA|COSTELA BOV|CARNE MOIDA|BIFE|BOVIN|MOCOTO|BUCHO|RABO BOV|FIGADO/.test(n)) return 'Bovinos';
 return 'Mercearia';
}
function montar(text){
 const r=parseCSV(text); if(r.length<2)return[]; const h=r[0].map(norm),idx=k=>h.indexOf(norm(k));
 const seen=new Set(),out=[];
 for(const a of r.slice(1)){const codigo=a[idx('Codigo')]||'',nome=(a[idx('Descricao_Produto')]||'').trim(),cat=a[idx('Categoria')]||'',preco=parsePreco(a[idx('Preco')]),un=(a[idx('Unidade')]||'UN').toLowerCase(),ncm=a[idx('NCM')]||''; if(!nome||!preco)continue; const grupo=(String(codigo).trim()==='000019'||String(codigo).trim()==='000020')?'Bovinos':classificar(nome,cat,ncm); if(!grupo)continue; if(grupo==='Mercearia'&&norm(cat)!=='MERCEARIA')continue; const codigoLimpo=String(codigo).trim(); const carne=['Bovinos','Suínos','Frangos'].includes(grupo); const codigoBalanca=/^000\d{3}$/.test(codigoLimpo); if(carne&&!codigoBalanca)continue; const key=`${codigo}|${nome}|${preco}|${un}`;if(seen.has(key))continue;seen.add(key);out.push({id:`P-${codigo}-${out.length}`,codigo,nome,preco,unidade:un==='kg'?'kg':'un',categoria:grupo,emoji:emoji[grupo]||'🛒'});}
 return out;
}
export default function App(){
 const [produtos,setProdutos]=useState([]),[loading,setLoading]=useState(true),[categoria,setCategoria]=useState('Bovinos'),[busca,setBusca]=useState(''),[qtd,setQtd]=useState({}),[recebimento,setRecebimento]=useState('Delivery'),[endereco,setEndereco]=useState(''),[bairro,setBairro]=useState(''),[pagamento,setPagamento]=useState('Pix');
 useEffect(()=>{(async()=>{try{const a=Asset.fromModule(csvAsset);await a.downloadAsync();const res=await fetch(a.localUri||a.uri);setProdutos(montar(await res.text()));}catch(e){Alert.alert('Erro no catálogo','Não foi possível carregar os produtos.');}finally{setLoading(false);}})();},[]);
 const visiveis=useMemo(()=>produtos.filter(p=>{const n=norm(p.nome);let ok=p.categoria===categoria;if(p.categoria==='Bebidas'){if(categoria==='Bebidas')ok=true;else if(categoria==='Bebidas Alcoólicas')ok=/CERVEJA|ICE |VINHO|VODKA|WHISK|GIN |PINGA|CACHACA|PITU|CABARE|COROTE|CHOPP/.test(n);else if(categoria==='Refrigerantes')ok=/REFRIG|COCA|FANTA|SPRITE|GUARANA|SUKITA|CONVENCAO|JABOTI/.test(n);else if(categoria==='Energéticos')ok=/ENERGET|RED BULL|MONSTER|TNT/.test(n);else if(categoria==='Sucos')ok=/SUCO|NECTAR|SUFRESH|DEL VALLE/.test(n);else if(categoria==='Águas')ok=/AGUA|CRYSTAL/.test(n);else if(categoria==='Outras Bebidas')ok=!/CERVEJA|ICE |VINHO|VODKA|WHISK|GIN |PINGA|CACHACA|PITU|CABARE|COROTE|CHOPP|REFRIG|COCA|FANTA|SPRITE|GUARANA|SUKITA|CONVENCAO|JABOTI|ENERGET|RED BULL|MONSTER|TNT|SUCO|NECTAR|SUFRESH|DEL VALLE|AGUA|CRYSTAL/.test(n);}return ok&&(!busca.trim()||norm(`${p.nome} ${p.codigo}`).includes(norm(busca)));}),[produtos,categoria,busca]);
 const alterar=(p,d)=>setQtd(x=>{const passo=p.unidade==='kg'?0.5:1,n=Math.max(0,Number(((x[p.id]||0)+d*passo).toFixed(2)));return{...x,[p.id]:n}});
 const carrinho=useMemo(()=>produtos.filter(p=>(qtd[p.id]||0)>0).map(p=>({...p,quantidade:qtd[p.id]})),[produtos,qtd]);
 const total=useMemo(()=>carrinho.reduce((s,p)=>s+p.preco*p.quantidade,0),[carrinho]);
 const finalizar=async()=>{if(!carrinho.length)return Alert.alert('Carrinho vazio','Adicione algum produto.');if(recebimento==='Delivery'&&!endereco.trim())return Alert.alert('Informe o endereço','Digite o endereço de entrega.');const itens=carrinho.map(p=>`• ${p.nome} — ${p.unidade==='kg'?p.quantidade.toFixed(2).replace('.',',')+' kg':p.quantidade+' un'} — ${dinheiro(p.preco*p.quantidade)}`).join('\n');const ent=recebimento==='Delivery'?`🚚 Delivery\n📍 ${endereco}\n🏘️ ${bairro||'Bairro não informado'}`:'🏪 Retirada no Açougue do Alemão';const msg=`Olá! Quero fazer um pedido no Açougue do Alemão 🥩\n\n🛒 PEDIDO\n${itens}\n\n💰 TOTAL: ${dinheiro(total)}\n\n${ent}\n\n💳 Pagamento: ${pagamento}`;await Linking.openURL(`https://wa.me/5511975187941?text=${encodeURIComponent(msg)}`)};
 return <View style={s.safe}><StatusBar style="light"/><ScrollView style={s.container} contentContainerStyle={{paddingBottom:110}} keyboardShouldPersistTaps="handled">
  <View style={s.topo}><Image source={logo} style={s.logo} resizeMode="contain"/><Text style={s.brand}>AÇOUGUE DO ALEMÃO</Text><Text style={s.sub}>Casa de Carnes & Mercearia</Text></View>
  <View style={s.hero}><Text style={s.heroMini}>🛵 DELIVERY • 🏪 RETIRADA</Text><Text style={s.heroTitle}>Peça sem sair de casa</Text><Text style={s.heroText}>Carnes, mercearia e bebidas em um só lugar.</Text></View>
  <TextInput style={s.search} value={busca} onChangeText={setBusca} placeholder="🔎 Buscar produto ou código..." placeholderTextColor="#777"/>
  <Text style={s.title}>🛒 Nossos produtos</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.cats}>{categorias.map(x=><TouchableOpacity key={x} style={[s.cat,categoria===x&&s.active]} onPress={()=>{setCategoria(x);setBusca('')}}><Text style={[s.catText,categoria===x&&s.activeText]}>{emoji[x]} {x}</Text></TouchableOpacity>)}</ScrollView>
  <Text style={s.count}>{loading?'Carregando catálogo...':`${visiveis.length} produtos encontrados`}</Text>
  {visiveis.map(p=><View style={s.card} key={p.id}><Text style={s.em}>{p.emoji}</Text><View style={s.info}><Text style={s.name}>{p.nome}</Text><Text style={s.code}>Cód. {p.codigo||'-'}</Text><Text style={s.price}>{dinheiro(p.preco)}<Text style={s.unit}>/{p.unidade}</Text></Text><Text style={s.hint}>{p.unidade==='kg'?'Mínimo 500 g • de 500 g em 500 g':'Venda por unidade'}</Text></View><View style={s.qty}><TouchableOpacity style={s.qbtn} onPress={()=>alterar(p,-1)}><Text style={s.qtxt}>−</Text></TouchableOpacity><Text style={s.qvalue}>{p.unidade==='kg'?`${(qtd[p.id]||0).toFixed(2).replace('.',',')} kg`:`${qtd[p.id]||0} un`}</Text><TouchableOpacity style={[s.qbtn,s.plus]} onPress={()=>alterar(p,1)}><Text style={s.qtxt}>+</Text></TouchableOpacity></View></View>)}
  <View style={s.cart}><Text style={s.cartTitle}>🛒 Seu carrinho</Text>{!carrinho.length?<Text style={s.empty}>Seu carrinho ainda está vazio.</Text>:carrinho.map(p=><View style={s.line} key={p.id}><Text style={s.item}>{p.nome} × {p.quantidade}</Text><Text style={s.val}>{dinheiro(p.preco*p.quantidade)}</Text></View>)}<View style={s.total}><Text style={s.totalT}>TOTAL</Text><Text style={s.totalV}>{dinheiro(total)}</Text></View></View>
  <Text style={s.title}>🚚 Como deseja receber?</Text><View style={s.row}>{['Delivery','Retirada'].map(x=><TouchableOpacity key={x} style={[s.opt,recebimento===x&&s.active]} onPress={()=>setRecebimento(x)}><Text style={[s.optT,recebimento===x&&s.activeText]}>{x}</Text></TouchableOpacity>)}</View>{recebimento==='Delivery'&&<View style={s.form}><TextInput style={s.input} value={endereco} onChangeText={setEndereco} placeholder="Rua, número e complemento"/><TextInput style={s.input} value={bairro} onChangeText={setBairro} placeholder="Bairro"/></View>}
  <Text style={s.title}>💳 Forma de pagamento</Text><View style={s.row}>{['Pix','Débito','Crédito'].map(x=><TouchableOpacity key={x} style={[s.opt,pagamento===x&&s.active]} onPress={()=>setPagamento(x)}><Text style={[s.optT,pagamento===x&&s.activeText]}>{x}</Text></TouchableOpacity>)}</View>
  <TouchableOpacity style={s.whats} onPress={finalizar}><Text style={s.whatsT}>📲 FINALIZAR PEDIDO NO WHATSAPP</Text></TouchableOpacity><Text style={s.address}>📍 Rua Maringá, 216 — Jundiaí</Text>
 </ScrollView>{carrinho.length>0&&<View style={s.float}><Text style={s.floatT}>🛒 {carrinho.length} produtos</Text><Text style={s.floatV}>{dinheiro(total)}</Text></View>}</View>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0b0b0b'},container:{flex:1,backgroundColor:'#f5f1eb'},topo:{backgroundColor:'#0b0b0b',alignItems:'center',paddingBottom:22},logo:{width:'100%',height:150},brand:{color:'#fff',fontSize:27,fontWeight:'900'},sub:{color:'#e1b44f',fontSize:15,fontWeight:'700'},hero:{margin:18,padding:22,borderRadius:24,backgroundColor:'#b4161e'},heroMini:{color:'#ffd36b',fontSize:12,fontWeight:'900'},heroTitle:{color:'#fff',fontSize:28,fontWeight:'900',marginTop:7},heroText:{color:'#fff',fontSize:16,marginTop:7},search:{backgroundColor:'#fff',marginHorizontal:18,padding:17,borderRadius:18,fontSize:16},title:{fontSize:23,fontWeight:'900',marginHorizontal:18,marginTop:24,marginBottom:12},cats:{paddingHorizontal:16,paddingBottom:10},cat:{backgroundColor:'#fff',paddingHorizontal:18,paddingVertical:12,borderRadius:25,marginRight:8},active:{backgroundColor:'#b51920'},catText:{fontWeight:'900'},activeText:{color:'#fff'},count:{marginHorizontal:20,color:'#777',fontWeight:'700',marginBottom:7},card:{backgroundColor:'#fff',marginHorizontal:16,marginVertical:6,padding:14,borderRadius:20,flexDirection:'row',alignItems:'center'},em:{fontSize:28,marginRight:10},info:{flex:1},name:{fontSize:15,fontWeight:'900'},code:{fontSize:11,color:'#999',marginTop:2},price:{fontSize:18,fontWeight:'900',color:'#b51920',marginTop:4},unit:{fontSize:12},hint:{fontSize:10,color:'#777'},qty:{alignItems:'center'},qbtn:{width:40,height:40,borderRadius:12,backgroundColor:'#111',alignItems:'center',justifyContent:'center'},plus:{backgroundColor:'#b51920'},qtxt:{color:'#fff',fontSize:23,fontWeight:'900'},qvalue:{fontSize:11,fontWeight:'900',paddingVertical:5},cart:{backgroundColor:'#111',margin:18,padding:20,borderRadius:22},cartTitle:{color:'#fff',fontSize:22,fontWeight:'900',marginBottom:10},empty:{color:'#bbb'},line:{flexDirection:'row',justifyContent:'space-between',paddingVertical:5},item:{color:'#fff',flex:1},val:{color:'#fff',fontWeight:'800'},total:{borderTopWidth:1,borderTopColor:'#555',marginTop:12,paddingTop:12,flexDirection:'row',justifyContent:'space-between'},totalT:{color:'#fff',fontSize:19,fontWeight:'900'},totalV:{color:'#d9ad54',fontSize:21,fontWeight:'900'},row:{flexDirection:'row',marginHorizontal:14},opt:{flex:1,backgroundColor:'#fff',padding:15,borderRadius:14,marginHorizontal:4,alignItems:'center'},optT:{fontWeight:'900'},form:{margin:18},input:{backgroundColor:'#fff',padding:15,borderRadius:14,marginBottom:9},whats:{backgroundColor:'#25D366',margin:18,padding:19,borderRadius:18,alignItems:'center'},whatsT:{color:'#fff',fontWeight:'900'},address:{textAlign:'center',color:'#555'},float:{position:'absolute',left:14,right:14,bottom:14,backgroundColor:'#111',borderRadius:18,padding:16,flexDirection:'row',justifyContent:'space-between',borderWidth:2,borderColor:'#d9ad54'},floatT:{color:'#fff',fontWeight:'900'},floatV:{color:'#e4b650',fontWeight:'900',fontSize:17}});