export const mercearia = [
  { codigo: 'M9-1', nome: 'MOLHO TOMATE FUGINI 300G TRADICIONAL', preco: 2.00, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M1762-1', nome: 'LEITE MOÇA NESTLE 395G', preco: 10.99, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M429-1', nome: 'DOCES DIVERSOS', preco: 3.00, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M29-1', nome: 'MACARRÃO INSTANTÂNEO APTI 70G CARNE', preco: 1.50, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M173-1', nome: 'CREME DE LEITE PIRACANJUBA 200G', preco: 3.99, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M1535-1', nome: 'CAFÉ PILÃO TRADICIONAL 500G', preco: 29.90, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M1195-1', nome: 'ÓLEO SOYA 900ML', preco: 9.90, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M16-1', nome: 'TEMPERO SAZON 60G VERMELHO', preco: 7.19, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M17-1', nome: 'LEITE CONDENSADO ITALAC 395G', preco: 8.80, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M164-1', nome: 'AÇÚCAR REFINADO 1KG', preco: 5.99, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M421-1', nome: 'AMENDOIM NOVIDADE 200G', preco: 7.00, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M204-1', nome: 'MILHO VERDE PREDILECTA 170G', preco: 3.90, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M136-1', nome: 'MACARRÃO INSTANTÂNEO APTI 70G GALINHA CAIPIRA', preco: 1.50, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M15-1', nome: 'EXTRATO DE TOMATE ELEFANTE 300G', preco: 8.90, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M426-1', nome: 'BATATA CHIPS 80G', preco: 4.80, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M228-1', nome: 'CREME DE LEITE ITALAC 200G', preco: 3.99, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M1855-1', nome: 'BISCOITO ITAMARATY LOOK 55G CHOCOLATE', preco: 3.59, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M420-1', nome: 'AMENDOIM SEM PELE 200G', preco: 7.00, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M139-1', nome: 'MOLHO TOMATE SALSARETTI 300G TRADICIONAL', preco: 2.70, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M588-1', nome: 'PÃO DE ALHO PREA', preco: 14.50, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M107-1', nome: 'REFRESCO TANG 18G LARANJA', preco: 2.00, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M603-1', nome: 'MACARRÃO DONA BENTA 500G ESPAGUETE', preco: 4.40, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M1147-1', nome: 'PRESTÍGIO 33G', preco: 2.99, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M2416-1', nome: 'QUEIJO RALADO MOCOCA 40G', preco: 4.60, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M2393-1', nome: 'BISCOITO TRAKINAS MORANGO 126G', preco: 3.60, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M112-1', nome: 'REFRESCO TANG 18G MARACUJÁ', preco: 2.00, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M620-1', nome: 'FARINHA DE MILHO BIJU 500G', preco: 7.99, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M237-1', nome: 'BISCOITO BAUDUCCO WAFER 140G CHOCOLATE', preco: 4.90, unidade: 'UN', categoria: 'Mercearia' },{ codigo: 'M118-1', nome: 'BISCOITO TUCS DIN CRACKERS 100G', preco: 2.00, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M28-1', nome: 'PAPEL HIGIENICO PALOMA C/4 FL.DP 30MT', preco: 6.90, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M132-1', nome: 'FLOCAO DE MILHO SINHA 500G', preco: 2.90, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: '7896508200034', nome: 'ACUCAR ALTO ALEGRE 1KG', preco: 5.99, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M419-1', nome: 'AMENDOIM JAPONES 200G', preco: 7.00, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M1739-1', nome: 'FAROFA PRONTA 400G', preco: 5.99, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M177-1', nome: 'AZEITONA VERDE VALE FERTIL 120G FATIADO', preco: 7.90, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M957-1', nome: 'REQUEIJAO TRADICIONAL TIROLEZ 200G', preco: 9.50, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M222-1', nome: 'MACARRAO GALO 500G SEMOLA PARAFUSO', preco: 4.90, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M1185-1', nome: 'BATATA PALHA 101G', preco: 7.50, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M236-1', nome: 'BISCOITO TRAKINAS 126G CHOCOLATE', preco: 3.50, unidade: 'UN', categoria: 'Mercearia' },
  { codigo: 'M1375-1', nome: 'FOLHA DE PAPEL ALUMINIO', preco: 4.70, unidade: 'UN', categoria: 'Mercearia' },

  { codigo: 'M824-1', nome: 'CERVEJA SKOL PILSEN 350ML', preco: 4.50, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M73-1', nome: 'CERVEJA ITAIPAVA PILSEN 350ML', preco: 4.00, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M867-1', nome: 'SKOL 269ML', preco: 4.00, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M1405-1', nome: 'HEINEKEN LATA 350ML', preco: 6.50, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M993-1', nome: 'CERVEJA IMPERIO PILSEN 350ML', preco: 4.50, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M837-1', nome: 'HEINEKEN LONG NECK 330ML', preco: 8.00, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M597-1', nome: 'CERVEJA PETRA 350ML', preco: 4.50, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M1431-1', nome: 'BRAHMA ZERO LATA 350ML', preco: 6.50, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M1175-1', nome: 'AMSTEL 269ML', preco: 4.00, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M865-1', nome: 'CERVEJA BRAHMA DUPLO MALTE 350ML', preco: 5.50, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M869-1', nome: 'CERVEJA AMSTEL LAGER 350ML', preco: 5.00, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M860-1', nome: 'CERVEJA BRAHMA CHOPP 350ML', preco: 4.50, unidade: 'UN', categoria: 'Cervejas' },
  { codigo: 'M899-1', nome: 'CERVEJA STELLA ARTOIS 330ML', preco: 8.50, unidade: 'UN', categoria: 'Cervejas' },
];